-- ============================================================================
-- SEED DE PREGUNTAS
-- 50 preguntas x 3 categorias x 3 niveles = 450 preguntas
-- Categorias: 1 = Historia | 2 = Deportes | 3 = Cultura
-- NOTA: la tabla `preguntas` NO tiene columna `nivel` (se calcula dinamico
--       segun aciertos en PartidaModel). El nivel de cada bloque es de CONTENIDO.
-- respuesta_correcta en minuscula: a / b / c / d
-- estado toma su valor por defecto: 'activa'
-- ============================================================================

USE juego;

-- ============================================================================
-- HISTORIA (categoria_id = 1)
-- ============================================================================

-- ---------- HISTORIA - NIVEL 1 (FACIL) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿En qué continente se encuentra Egipto?', 'América', 'África', 'Asia', 'Europa', 'b', 1),
('¿Qué medio de transporte usaban principalmente los vikingos?', 'Aviones', 'Trenes', 'Barcos', 'Autos', 'c', 1),
('¿Con qué material se construían las pirámides de Egipto?', 'Madera', 'Piedra', 'Vidrio', 'Plástico', 'b', 1),
('¿Quién descubrió América en 1492?', 'Napoleón', 'Cristóbal Colón', 'Julio César', 'Marco Polo', 'b', 1),
('¿En qué país nacieron los Juegos Olímpicos antiguos?', 'Italia', 'Egipto', 'Grecia', 'China', 'c', 1),
('¿Qué animal usaban los soldados a caballo en las batallas antiguas?', 'Elefante', 'Caballo', 'Camello', 'León', 'b', 1),
('¿Cómo se llamaban los reyes de Egipto?', 'Emperadores', 'Faraones', 'Zares', 'Sultanes', 'b', 1),
('¿Qué construían los romanos para llevar agua a las ciudades?', 'Puentes', 'Acueductos', 'Túneles', 'Molinos', 'b', 1),
('¿En qué siglo vivimos actualmente?', 'Siglo XIX', 'Siglo XX', 'Siglo XXI', 'Siglo XVIII', 'c', 1),
('¿Qué famoso muro estaba en Alemania?', 'Muro de China', 'Muro de Berlín', 'Muro de Adriano', 'Muro de Troya', 'b', 1),
('¿Quién fue el libertador de Argentina, Chile y Perú?', 'Simón Bolívar', 'José de San Martín', 'Manuel Belgrano', 'Bernardo O''Higgins', 'b', 1),
('¿Qué creó Johannes Gutenberg?', 'El teléfono', 'La imprenta', 'La rueda', 'El reloj', 'b', 1),
('¿En qué país está la Gran Muralla?', 'Japón', 'India', 'China', 'Corea', 'c', 1),
('¿Quién pintó La Mona Lisa?', 'Picasso', 'Leonardo da Vinci', 'Miguel Ángel', 'Van Gogh', 'b', 1),
('¿Qué civilización antigua vivió en el actual México?', 'Vikingos', 'Aztecas', 'Romanos', 'Egipcios', 'b', 1),
('¿Cuántos años tiene un siglo?', '10', '50', '100', '1000', 'c', 1),
('¿En qué país está la ciudad de Roma?', 'España', 'Grecia', 'Italia', 'Francia', 'c', 1),
('¿Qué usaban los hombres primitivos para hacer fuego?', 'Fósforos', 'Piedras', 'Encendedores', 'Electricidad', 'b', 1),
('¿Quién fue el primer presidente de Estados Unidos?', 'Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams', 'b', 1),
('¿Qué imperio conquistó gran parte de Europa en la antigüedad?', 'Imperio Romano', 'Imperio Japonés', 'Imperio Azteca', 'Imperio Inca', 'a', 1),
('¿En qué continente vivieron los mayas?', 'Europa', 'América', 'Asia', 'África', 'b', 1),
('¿Qué barco famoso se hundió en 1912?', 'Titanic', 'Santa María', 'Beagle', 'Mayflower', 'a', 1),
('¿Quién escribió Don Quijote de la Mancha?', 'Shakespeare', 'Cervantes', 'Borges', 'Neruda', 'b', 1),
('¿Qué animal ayudó a cruzar los Alpes al ejército de Aníbal?', 'Caballos', 'Elefantes', 'Camellos', 'Perros', 'b', 1),
('¿De qué país era originario Napoleón Bonaparte?', 'España', 'Francia', 'Italia', 'Alemania', 'b', 1),
('¿Qué se celebra el 25 de mayo en Argentina?', 'La Independencia', 'La Revolución de Mayo', 'El Día del Trabajador', 'La Batalla de Salta', 'b', 1),
('¿En qué país se originó el Imperio Inca?', 'México', 'Perú', 'Brasil', 'Chile', 'b', 1),
('¿Qué instrumento usaban los marineros para orientarse?', 'Reloj', 'Brújula', 'Termómetro', 'Regla', 'b', 1),
('¿Quién creó la teoría de la relatividad?', 'Newton', 'Einstein', 'Galileo', 'Darwin', 'b', 1),
('¿Qué océano cruzó Colón para llegar a América?', 'Pacífico', 'Atlántico', 'Índico', 'Ártico', 'b', 1),
('¿En qué país se construyó el Coliseo?', 'Grecia', 'Italia', 'Egipto', 'Turquía', 'b', 1),
('¿Qué metal precioso buscaban los conquistadores en América?', 'Hierro', 'Oro', 'Cobre', 'Aluminio', 'b', 1),
('¿Cómo se llamaba el barco de Cristóbal Colón más famoso?', 'Titanic', 'Santa María', 'Victoria', 'Beagle', 'b', 1),
('¿Qué antigua ciudad quedó sepultada por el volcán Vesubio?', 'Atenas', 'Pompeya', 'Cartago', 'Esparta', 'b', 1),
('¿En qué país gobernaban los zares?', 'Alemania', 'Rusia', 'Francia', 'Inglaterra', 'b', 1),
('¿Qué famoso científico dijo que la Tierra gira alrededor del Sol?', 'Colón', 'Galileo', 'Aristóteles', 'Edison', 'b', 1),
('¿Qué guerreros japoneses usaban espadas llamadas katanas?', 'Vikingos', 'Samuráis', 'Gladiadores', 'Cruzados', 'b', 1),
('¿Cuál fue la primera mujer en muchos países en no poder votar antiguamente?', 'Las niñas', 'Las mujeres', 'Las ancianas', 'Las reinas', 'b', 1),
('¿En qué continente está la ciudad de El Cairo?', 'Asia', 'África', 'Europa', 'América', 'b', 1),
('¿Qué antigua maravilla estaba en Egipto?', 'Coliseo', 'Las pirámides de Giza', 'Torre Eiffel', 'Muralla China', 'b', 1),
('¿Quién lideró la independencia de la India de forma pacífica?', 'Mandela', 'Gandhi', 'Lincoln', 'Churchill', 'b', 1),
('¿Qué usaban los egipcios para escribir?', 'Papel moderno', 'Papiro', 'Cartón', 'Vidrio', 'b', 1),
('¿En qué país nació la democracia antigua?', 'Roma', 'Grecia', 'Egipto', 'Persia', 'b', 1),
('¿Qué dinosaurio NO existió junto a los humanos?', 'Ninguno, no coincidieron', 'El T-Rex sí', 'El velociraptor sí', 'Todos convivieron', 'a', 1),
('¿Qué famoso rey inglés tuvo seis esposas?', 'Ricardo I', 'Enrique VIII', 'Jorge III', 'Eduardo I', 'b', 1),
('¿Qué continente fue el último en ser explorado por completo?', 'África', 'Antártida', 'Europa', 'Asia', 'b', 1),
('¿Quién fue el famoso emperador francés derrotado en Waterloo?', 'Luis XIV', 'Napoleón', 'Carlomagno', 'De Gaulle', 'b', 1),
('¿Qué antigua civilización construyó Machu Picchu?', 'Aztecas', 'Incas', 'Mayas', 'Olmecas', 'b', 1),
('¿En qué país se encuentra la Torre Eiffel?', 'Italia', 'Francia', 'España', 'Bélgica', 'b', 1),
('¿Qué se firmó para terminar una guerra entre países?', 'Un contrato', 'Un tratado de paz', 'Una factura', 'Un recibo', 'b', 1);

-- ---------- HISTORIA - NIVEL 2 (INTERMEDIO) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿En qué año comenzó la Segunda Guerra Mundial?', '1914', '1939', '1945', '1929', 'b', 1),
('¿Quién fue el primer presidente constitucional de Argentina?', 'Domingo Sarmiento', 'Bernardino Rivadavia', 'Justo José de Urquiza', 'Bartolomé Mitre', 'c', 1),
('¿En qué año cayó el Muro de Berlín?', '1985', '1989', '1991', '1979', 'b', 1),
('¿Qué imperio fue gobernado por Julio César?', 'Griego', 'Romano', 'Persa', 'Otomano', 'b', 1),
('¿En qué año se declaró la independencia de Argentina?', '1810', '1816', '1820', '1806', 'b', 1),
('¿Quién escribió el Manifiesto Comunista junto a Engels?', 'Lenin', 'Karl Marx', 'Stalin', 'Trotsky', 'b', 1),
('¿Qué reina apoyó el viaje de Colón a América?', 'Isabel I de Inglaterra', 'Isabel la Católica', 'María Antonieta', 'Victoria', 'b', 1),
('¿En qué siglo ocurrió la Revolución Francesa?', 'Siglo XVII', 'Siglo XVIII', 'Siglo XIX', 'Siglo XVI', 'b', 1),
('¿Qué civilización desarrolló el sistema de escritura cuneiforme?', 'Egipcios', 'Sumerios', 'Griegos', 'Mayas', 'b', 1),
('¿Quién fue el líder de la Alemania nazi?', 'Mussolini', 'Adolf Hitler', 'Franco', 'Stalin', 'b', 1),
('¿En qué año llegó el hombre a la Luna?', '1965', '1969', '1972', '1959', 'b', 1),
('¿Qué país lanzó las primeras bombas atómicas en la guerra?', 'Alemania', 'Estados Unidos', 'Rusia', 'Japón', 'b', 1),
('¿Quién fue el general cartaginés que enfrentó a Roma?', 'César', 'Aníbal', 'Alejandro', 'Espartaco', 'b', 1),
('¿En qué año se hundió el Titanic?', '1905', '1912', '1920', '1898', 'b', 1),
('¿Qué revolución transformó la producción con las máquinas de vapor?', 'Revolución Francesa', 'Revolución Industrial', 'Revolución Rusa', 'Revolución Cubana', 'b', 1),
('¿Quién conquistó el Imperio Azteca?', 'Francisco Pizarro', 'Hernán Cortés', 'Vasco de Gama', 'Magallanes', 'b', 1),
('¿En qué año terminó la Segunda Guerra Mundial?', '1943', '1945', '1948', '1950', 'b', 1),
('¿Quién fue el conquistador del Imperio Inca?', 'Hernán Cortés', 'Francisco Pizarro', 'Colón', 'Cabral', 'b', 1),
('¿Qué documento firmaron los Estados Unidos en 1776?', 'La Constitución', 'La Declaración de Independencia', 'El Tratado de Versalles', 'La Carta Magna', 'b', 1),
('¿Qué imperio dominó gran parte de Asia bajo Genghis Khan?', 'Imperio Persa', 'Imperio Mongol', 'Imperio Otomano', 'Imperio Chino', 'b', 1),
('¿En qué país comenzó la Revolución Industrial?', 'Francia', 'Inglaterra', 'Alemania', 'Estados Unidos', 'b', 1),
('¿Quién lideró la Revolución Rusa de 1917?', 'Stalin', 'Lenin', 'Gorbachov', 'Trotsky', 'b', 1),
('¿Qué guerra enfrentó al Norte y al Sur de Estados Unidos?', 'Guerra de Independencia', 'Guerra Civil', 'Guerra Fría', 'Guerra de Vietnam', 'b', 1),
('¿Quién fue conocido como el Libertador de América del Sur en el norte?', 'San Martín', 'Simón Bolívar', 'Belgrano', 'Artigas', 'b', 1),
('¿En qué año comenzó la Primera Guerra Mundial?', '1905', '1914', '1918', '1920', 'b', 1),
('¿Qué famoso faraón murió muy joven y su tumba fue hallada intacta?', 'Ramsés II', 'Tutankamón', 'Keops', 'Akenatón', 'b', 1),
('¿Quién creó el ejército de los Diez Mil y conquistó Persia?', 'Julio César', 'Alejandro Magno', 'Aníbal', 'Darío', 'b', 1),
('¿Qué muro dividió Europa durante la Guerra Fría de forma simbólica?', 'Muro de Adriano', 'Telón de Acero', 'Muralla China', 'Muro de las Lamentaciones', 'b', 1),
('¿Quién creó la bandera de Argentina?', 'San Martín', 'Manuel Belgrano', 'Rivadavia', 'Moreno', 'b', 1),
('¿En qué ciudad se firmó el tratado que terminó la Primera Guerra Mundial?', 'Londres', 'Versalles', 'Viena', 'Ginebra', 'b', 1),
('¿Qué explorador dio la primera vuelta al mundo (su expedición)?', 'Colón', 'Magallanes', 'Vasco de Gama', 'Cabral', 'b', 1),
('¿Qué civilización construyó Chichén Itzá?', 'Aztecas', 'Mayas', 'Incas', 'Toltecas', 'b', 1),
('¿Quién fue la reina egipcia aliada de Julio César y Marco Antonio?', 'Nefertiti', 'Cleopatra', 'Hatshepsut', 'Isis', 'b', 1),
('¿En qué año comenzó la Revolución Francesa?', '1776', '1789', '1804', '1799', 'b', 1),
('¿Qué imperio cayó en 1453 con la toma de Constantinopla?', 'Imperio Romano de Occidente', 'Imperio Bizantino', 'Imperio Persa', 'Imperio Mongol', 'b', 1),
('¿Quién fue el primer emperador de Roma?', 'Julio César', 'Augusto', 'Nerón', 'Trajano', 'b', 1),
('¿Qué batalla definió la independencia sudamericana en 1824?', 'Batalla de Maipú', 'Batalla de Ayacucho', 'Batalla de Boyacá', 'Batalla de Chacabuco', 'b', 1),
('¿Qué peste mató a un tercio de la población europea en el siglo XIV?', 'Viruela', 'Peste Negra', 'Cólera', 'Gripe', 'b', 1),
('¿Quién fue el líder de la India en su independencia como primer ministro?', 'Gandhi', 'Nehru', 'Bose', 'Patel', 'b', 1),
('¿Qué país colonizó Brasil?', 'España', 'Portugal', 'Francia', 'Inglaterra', 'b', 1),
('¿En qué año se abolió la esclavitud en Estados Unidos?', '1850', '1865', '1880', '1900', 'b', 1),
('¿Quién fue el famoso rey sol de Francia?', 'Luis XIV', 'Luis XVI', 'Napoleón', 'Carlos V', 'a', 1),
('¿Qué antigua ciudad estado griega era famosa por sus guerreros?', 'Atenas', 'Esparta', 'Corinto', 'Tebas', 'b', 1),
('¿Qué tratado dividió el Nuevo Mundo entre España y Portugal?', 'Tratado de París', 'Tratado de Tordesillas', 'Tratado de Utrecht', 'Tratado de Viena', 'b', 1),
('¿Quién encabezó la Larga Marcha en China?', 'Sun Yat-sen', 'Mao Zedong', 'Deng Xiaoping', 'Chiang Kai-shek', 'b', 1),
('¿En qué año se produjo la caída del Imperio Romano de Occidente?', '476', '1453', '312', '800', 'a', 1),
('¿Qué revolución de 1959 llevó a Fidel Castro al poder?', 'Revolución Mexicana', 'Revolución Cubana', 'Revolución Rusa', 'Revolución China', 'b', 1),
('¿Qué famosa carta limitó el poder del rey en Inglaterra en 1215?', 'Constitución', 'Carta Magna', 'Declaración de Derechos', 'Acta de Unión', 'b', 1),
('¿Quién descubrió el paso hacia el océano Pacífico por el sur de América?', 'Colón', 'Magallanes', 'Cabral', 'Elcano', 'b', 1),
('¿Qué guerra enfrentó a Estados Unidos y la Unión Soviética sin combate directo?', 'Guerra de Corea', 'Guerra Fría', 'Guerra del Golfo', 'Guerra de Vietnam', 'b', 1);

-- ---------- HISTORIA - NIVEL 3 (DIFICIL) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿En qué año exacto fue la Batalla de Hastings?', '1066', '1088', '1042', '1100', 'a', 1),
('¿Cuántos años duró oficialmente la Guerra de los Cien Años?', '100', '116', '99', '120', 'b', 1),
('¿Quién fue el primer emperador de la dinastía Qin en China?', 'Han Wudi', 'Qin Shi Huang', 'Kublai Khan', 'Sun Tzu', 'b', 1),
('¿En qué año se firmó la Paz de Westfalia?', '1618', '1648', '1659', '1700', 'b', 1),
('¿Qué emperador bizantino ordenó recopilar el Corpus Iuris Civilis?', 'Constantino', 'Justiniano I', 'Heraclio', 'Basilio II', 'b', 1),
('¿En qué año fue coronado Carlomagno como emperador?', '742', '800', '814', '768', 'b', 1),
('¿Cuál fue la primera nación en otorgar el voto femenino a nivel nacional en 1893?', 'Estados Unidos', 'Nueva Zelanda', 'Australia', 'Finlandia', 'b', 1),
('¿Qué tratado puso fin a la Guerra de Sucesión Española?', 'Tratado de Tordesillas', 'Tratado de Utrecht', 'Tratado de Versalles', 'Paz de Augsburgo', 'b', 1),
('¿En qué año Constantinopla cayó ante los otomanos?', '1453', '1492', '1204', '1389', 'a', 1),
('¿Quién fue el arquitecto principal atribuido a la cúpula de Santa María del Fiore?', 'Bernini', 'Brunelleschi', 'Miguel Ángel', 'Bramante', 'b', 1),
('¿En qué batalla de 1815 fue derrotado definitivamente Napoleón?', 'Austerlitz', 'Waterloo', 'Leipzig', 'Borodino', 'b', 1),
('¿Qué dinastía gobernaba China cuando llegó Marco Polo?', 'Ming', 'Yuan', 'Song', 'Tang', 'b', 1),
('¿En qué año se produjo el Cisma de Oriente entre las iglesias?', '1054', '1204', '1378', '1517', 'a', 1),
('¿Quién lideró la revuelta de esclavos más famosa contra Roma?', 'Craso', 'Espartaco', 'Vercingétorix', 'Aníbal', 'b', 1),
('¿Qué rey firmó la Carta Magna en Inglaterra?', 'Ricardo Corazón de León', 'Juan sin Tierra', 'Enrique II', 'Eduardo I', 'b', 1),
('¿En qué año comenzó la Reforma Protestante con las 95 tesis?', '1492', '1517', '1534', '1555', 'b', 1),
('¿Qué imperio precolombino tenía su capital en Tenochtitlán?', 'Inca', 'Azteca', 'Maya', 'Chimú', 'b', 1),
('¿Quién fue el último emperador romano de Occidente?', 'Rómulo Augústulo', 'Teodosio', 'Honorio', 'Valentiniano III', 'a', 1),
('¿En qué año se firmó el Congreso de Viena que reordenó Europa?', '1789', '1815', '1848', '1871', 'b', 1),
('¿Qué faraón es famoso por intentar imponer el monoteísmo a Atón?', 'Ramsés II', 'Akenatón', 'Tutmosis III', 'Keops', 'b', 1),
('¿Cuál fue el nombre de la peste que asoló Atenas durante la Guerra del Peloponeso?', 'Peste de Justiniano', 'Peste de Atenas', 'Peste Negra', 'Peste Antonina', 'b', 1),
('¿Quién unificó a Italia como su primer rey en 1861?', 'Garibaldi', 'Víctor Manuel II', 'Cavour', 'Mazzini', 'b', 1),
('¿En qué año estalló la Comuna de París?', '1848', '1871', '1789', '1830', 'b', 1),
('¿Qué civilización desarrolló el calendario de la Cuenta Larga?', 'Azteca', 'Maya', 'Inca', 'Olmeca', 'b', 1),
('¿Quién fue el canciller que unificó Alemania en 1871?', 'Guillermo I', 'Otto von Bismarck', 'Metternich', 'Adenauer', 'b', 1),
('¿En qué año se produjo la Defenestración de Praga que inició la Guerra de los Treinta Años?', '1618', '1648', '1600', '1555', 'a', 1),
('¿Qué emperador romano legalizó el cristianismo con el Edicto de Milán?', 'Nerón', 'Constantino', 'Diocleciano', 'Teodosio', 'b', 1),
('¿Quién fue el shogun que unificó Japón e inició el período Edo?', 'Oda Nobunaga', 'Tokugawa Ieyasu', 'Toyotomi Hideyoshi', 'Minamoto', 'b', 1),
('¿En qué año se produjo la Revolución Gloriosa en Inglaterra?', '1642', '1688', '1707', '1660', 'b', 1),
('¿Qué tratado de 1494 dividió el mundo entre España y Portugal?', 'Tratado de Zaragoza', 'Tratado de Tordesillas', 'Tratado de Alcáçovas', 'Tratado de Cateau', 'b', 1),
('¿Quién fue el emperador azteca al momento de la llegada de Cortés?', 'Cuauhtémoc', 'Moctezuma II', 'Nezahualcóyotl', 'Ahuízotl', 'b', 1),
('¿En qué siglo vivió el filósofo Confucio?', 'Siglo III a.C.', 'Siglo VI a.C.', 'Siglo I d.C.', 'Siglo IX a.C.', 'b', 1),
('¿Qué batalla naval de 1571 frenó la expansión otomana en el Mediterráneo?', 'Batalla de Lepanto', 'Batalla de Actium', 'Batalla de Salamina', 'Batalla de Trafalgar', 'a', 1),
('¿Quién fue la primera y única mujer faraón de gran importancia del Imperio Nuevo?', 'Nefertiti', 'Hatshepsut', 'Cleopatra', 'Nefertari', 'b', 1),
('¿En qué año se produjo la caída de Granada, fin de la Reconquista?', '1469', '1492', '1512', '1478', 'b', 1),
('¿Qué imperio africano fue famoso por su riqueza en oro bajo Mansa Musa?', 'Imperio Songhai', 'Imperio de Malí', 'Reino de Ghana', 'Imperio Etíope', 'b', 1),
('¿Quién escribió El Príncipe, tratado político del Renacimiento?', 'Erasmo', 'Maquiavelo', 'Tomás Moro', 'Dante', 'b', 1),
('¿En qué año se firmó la Declaración de Independencia de Estados Unidos?', '1774', '1776', '1783', '1787', 'b', 1),
('¿Qué dinastía china construyó la mayor parte de la Gran Muralla que se ve hoy?', 'Han', 'Ming', 'Tang', 'Qing', 'b', 1),
('¿Quién fue el líder de los hunos que amenazó Roma?', 'Alarico', 'Atila', 'Genserico', 'Odoacro', 'b', 1),
('¿En qué año fue asesinado Julio César?', '44 a.C.', '27 a.C.', '14 d.C.', '63 a.C.', 'a', 1),
('¿Qué reino medieval fue gobernado por Saladino?', 'Reino Franco', 'Sultanato Ayyubí', 'Imperio Bizantino', 'Reino de Jerusalén', 'b', 1),
('¿Cuál fue el primer código de leyes escrito conocido, del rey babilónico?', 'Ley de las XII Tablas', 'Código de Hammurabi', 'Código Justiniano', 'Edicto de Milán', 'b', 1),
('¿En qué año comenzó la Guerra de los Treinta Años?', '1600', '1618', '1648', '1555', 'b', 1),
('¿Qué explorador portugués llegó a la India por mar en 1498?', 'Magallanes', 'Vasco de Gama', 'Bartolomé Díaz', 'Cabral', 'b', 1),
('¿Quién fue el primer zar de Rusia en tomar oficialmente ese título?', 'Pedro el Grande', 'Iván IV el Terrible', 'Catalina la Grande', 'Boris Godunov', 'b', 1),
('¿En qué año fue la Noche de San Bartolomé en Francia?', '1572', '1598', '1610', '1547', 'a', 1),
('¿Qué civilización mesopotámica es conocida por su rey Nabucodonosor II?', 'Asiria', 'Babilonia', 'Sumeria', 'Persia', 'b', 1),
('¿Quién dirigió la expedición que completó la primera circunnavegación tras la muerte de Magallanes?', 'Pizarro', 'Juan Sebastián Elcano', 'Balboa', 'Cabral', 'b', 1),
('¿En qué año se produjo el Motín del Té de Boston?', '1765', '1773', '1776', '1781', 'b', 1);


-- ============================================================================
-- DEPORTES (categoria_id = 2)
-- ============================================================================

-- ---------- DEPORTES - NIVEL 1 (FACIL) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿Cuántos jugadores tiene un equipo de fútbol en cancha?', '9', '10', '11', '12', 'c', 2),
('¿Con qué parte del cuerpo NO se puede tocar la pelota en el fútbol (salvo el arquero)?', 'Pie', 'Cabeza', 'Manos', 'Pecho', 'c', 2),
('¿En qué deporte se usa una raqueta y una pelota amarilla?', 'Golf', 'Tenis', 'Vóley', 'Rugby', 'b', 2),
('¿Cuántos jugadores tiene un equipo de básquet en cancha?', '4', '5', '6', '7', 'b', 2),
('¿En qué deporte se hacen goles con un arco y un arquero?', 'Tenis', 'Fútbol', 'Golf', 'Natación', 'b', 2),
('¿Qué se usa para jugar al golf?', 'Raqueta', 'Palos', 'Guantes de box', 'Remos', 'b', 2),
('¿Cada cuántos años se realizan los Juegos Olímpicos de verano?', '2', '3', '4', '5', 'c', 2),
('¿En qué deporte destaca Lionel Messi?', 'Tenis', 'Fútbol', 'Básquet', 'Boxeo', 'b', 2),
('¿Cuántos aros tiene la bandera olímpica?', '4', '5', '6', '3', 'b', 2),
('¿En qué deporte se usa una pileta?', 'Ciclismo', 'Natación', 'Atletismo', 'Tenis', 'b', 2),
('¿Qué deporte se juega en Wimbledon?', 'Golf', 'Tenis', 'Cricket', 'Rugby', 'b', 2),
('¿Cuál es el objetivo en el fútbol?', 'Encestar', 'Meter goles', 'Hacer tantos con la mano', 'Cruzar la meta', 'b', 2),
('¿En qué deporte se usa un guante y una pelota pequeña dura?', 'Béisbol', 'Fútbol', 'Vóley', 'Handball', 'a', 2),
('¿Qué animal se usa en el deporte de la equitación?', 'Perro', 'Caballo', 'Toro', 'Camello', 'b', 2),
('¿Cuántos tiempos tiene un partido de fútbol?', '1', '2', '3', '4', 'b', 2),
('¿Qué color de tarjeta expulsa a un jugador en el fútbol?', 'Amarilla', 'Roja', 'Verde', 'Azul', 'b', 2),
('¿En qué deporte se anota un touchdown?', 'Rugby', 'Fútbol americano', 'Básquet', 'Hockey', 'b', 2),
('¿Qué deporte practica Rafael Nadal?', 'Golf', 'Tenis', 'Fútbol', 'Natación', 'b', 2),
('¿Cuánto dura cada tiempo reglamentario en el fútbol?', '30 minutos', '45 minutos', '60 minutos', '20 minutos', 'b', 2),
('¿En qué deporte se usan skís?', 'Natación', 'Esquí', 'Ciclismo', 'Boxeo', 'b', 2),
('¿Qué se necesita para jugar al tenis de mesa?', 'Un balón grande', 'Una paleta y pelotita', 'Un palo de hockey', 'Guantes', 'b', 2),
('¿Qué país es famoso por el tango y por Maradona?', 'Brasil', 'Argentina', 'España', 'Uruguay', 'b', 2),
('¿En qué deporte se corre los 100 metros llanos?', 'Natación', 'Atletismo', 'Ciclismo', 'Remo', 'b', 2),
('¿Con qué se golpea la pelota en el béisbol?', 'Raqueta', 'Bate', 'Palo de golf', 'Mano', 'b', 2),
('¿Cuál es el deporte más popular del mundo?', 'Básquet', 'Fútbol', 'Tenis', 'Golf', 'b', 2),
('¿En qué deporte se hace un mate o volcada?', 'Fútbol', 'Básquet', 'Tenis', 'Golf', 'b', 2),
('¿Qué deporte se juega sobre hielo con patines y un disco?', 'Curling', 'Hockey sobre hielo', 'Patinaje', 'Esquí', 'b', 2),
('¿Cuántos jugadores tiene un equipo de vóley en cancha?', '5', '6', '7', '8', 'b', 2),
('¿Qué se usa en boxeo para proteger las manos?', 'Raquetas', 'Guantes', 'Palos', 'Cascos de fútbol', 'b', 2),
('¿En qué deporte destacó Michael Jordan?', 'Fútbol', 'Básquet', 'Tenis', 'Béisbol', 'b', 2),
('¿Qué deporte usa una red alta y no se puede dejar caer la pelota?', 'Fútbol', 'Vóley', 'Golf', 'Boxeo', 'b', 2),
('¿En qué deporte se compite en una bicicleta?', 'Ciclismo', 'Remo', 'Atletismo', 'Natación', 'a', 2),
('¿Cuál es el máximo trofeo del fútbol entre selecciones?', 'Champions League', 'Copa del Mundo', 'Copa Libertadores', 'Europa League', 'b', 2),
('¿Qué deporte practican los nadadores?', 'Atletismo', 'Natación', 'Remo', 'Buceo', 'b', 2),
('¿En qué deporte hay un ring?', 'Tenis', 'Boxeo', 'Golf', 'Fútbol', 'b', 2),
('¿Qué necesitas para andar en skate?', 'Una pelota', 'Una patineta', 'Una raqueta', 'Un bate', 'b', 2),
('¿Qué deporte se juega en Roland Garros?', 'Golf', 'Tenis', 'Fútbol', 'Rugby', 'b', 2),
('¿Cuántos puntos vale un gol en el fútbol?', '1', '2', '3', '6', 'a', 2),
('¿Qué deporte usa una pelota ovalada y se juega con las manos y los pies?', 'Fútbol', 'Rugby', 'Vóley', 'Básquet', 'b', 2),
('¿En qué país se creó el fútbol moderno?', 'Brasil', 'Inglaterra', 'Argentina', 'España', 'b', 2),
('¿Qué se usa para jugar al hockey sobre césped?', 'Raqueta', 'Palo o stick', 'Guante', 'Bate', 'b', 2),
('¿En qué deporte compiten los pilotos de Fórmula 1?', 'Ciclismo', 'Automovilismo', 'Motociclismo', 'Atletismo', 'b', 2),
('¿Qué deporte practica una gimnasta?', 'Boxeo', 'Gimnasia', 'Golf', 'Remo', 'b', 2),
('¿Cuántos sets como mínimo puede durar un partido de tenis a 3 sets?', '1', '2', '3', '5', 'b', 2),
('¿Qué deporte usa una portería y palos, y se juega mucho en Canadá sobre hielo?', 'Fútbol', 'Hockey sobre hielo', 'Golf', 'Cricket', 'b', 2),
('¿Qué elemento se lanza en el deporte de la jabalina?', 'Una pelota', 'Una jabalina', 'Un disco', 'Un martillo', 'b', 2),
('¿En qué deporte se usa un balón y una canasta?', 'Fútbol', 'Básquet', 'Tenis', 'Golf', 'b', 2),
('¿Qué país ganó el Mundial de fútbol 2022?', 'Francia', 'Argentina', 'Brasil', 'Alemania', 'b', 2),
('¿Qué deporte se practica en una cancha con red en el medio y se golpea con la mano por debajo o por arriba?', 'Tenis', 'Vóley', 'Golf', 'Rugby', 'b', 2),
('¿En qué deporte se usa el término gol de penal?', 'Básquet', 'Fútbol', 'Tenis', 'Golf', 'b', 2);

-- ---------- DEPORTES - NIVEL 2 (INTERMEDIO) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿En qué país se jugaron los Juegos Olímpicos de 2016?', 'China', 'Brasil', 'Rusia', 'Japón', 'b', 2),
('¿Cuántos Grand Slam hay en el tenis por temporada?', '3', '4', '5', '6', 'b', 2),
('¿Qué selección ganó más Copas del Mundo de fútbol?', 'Argentina', 'Brasil', 'Alemania', 'Italia', 'b', 2),
('¿Cuánto mide la distancia de una maratón oficial?', '10 km', '21 km', '42 km', '50 km', 'c', 2),
('¿En qué deporte se destacó Usain Bolt?', 'Natación', 'Atletismo', 'Ciclismo', 'Boxeo', 'b', 2),
('¿Cuántos jugadores tiene un equipo de rugby en cancha (union)?', '11', '13', '15', '7', 'c', 2),
('¿Qué país organizó el Mundial de fútbol 2014?', 'Sudáfrica', 'Brasil', 'Rusia', 'Alemania', 'b', 2),
('¿En qué ciudad están las oficinas del Comité Olímpico Internacional?', 'París', 'Lausana', 'Roma', 'Atenas', 'b', 2),
('¿Cuántos puntos vale un triple en básquet?', '1', '2', '3', '4', 'c', 2),
('¿Qué tenista es conocido como el rey de la tierra batida?', 'Federer', 'Nadal', 'Djokovic', 'Murray', 'b', 2),
('¿Qué club ganó más veces la Champions League?', 'Barcelona', 'Real Madrid', 'Milan', 'Bayern', 'b', 2),
('¿En qué deporte se compite por el Tour de Francia?', 'Automovilismo', 'Ciclismo', 'Atletismo', 'Motociclismo', 'b', 2),
('¿Cuál es la máxima categoría del automovilismo mundial?', 'IndyCar', 'Fórmula 1', 'Rally', 'NASCAR', 'b', 2),
('¿Qué país ganó la Eurocopa 2021?', 'Inglaterra', 'Italia', 'España', 'Francia', 'b', 2),
('¿Cuántos minutos dura un partido de básquet en la NBA (tiempo total sin prórrogas)?', '40', '48', '60', '36', 'b', 2),
('¿En qué deporte se entrega el Balón de Oro?', 'Básquet', 'Fútbol', 'Tenis', 'Rugby', 'b', 2),
('¿Qué nadador ganó más medallas olímpicas en la historia?', 'Ian Thorpe', 'Michael Phelps', 'Mark Spitz', 'Caeleb Dressel', 'b', 2),
('¿Qué equipo de fútbol es apodado los Merengues?', 'Barcelona', 'Real Madrid', 'Atlético', 'Valencia', 'b', 2),
('¿En qué año Argentina ganó su primer Mundial de fútbol?', '1974', '1978', '1986', '1990', 'b', 2),
('¿Cuántos puntos vale un try en el rugby (union)?', '3', '5', '7', '2', 'b', 2),
('¿Qué corredor jamaicano posee el récord mundial de 100 metros?', 'Carl Lewis', 'Usain Bolt', 'Yohan Blake', 'Tyson Gay', 'b', 2),
('¿En qué deporte destaca Simone Biles?', 'Natación', 'Gimnasia artística', 'Atletismo', 'Tenis', 'b', 2),
('¿Qué país ganó el Mundial de fútbol 2018?', 'Croacia', 'Francia', 'Alemania', 'Brasil', 'b', 2),
('¿Cuántos hoyos tiene un campo de golf estándar?', '9', '18', '24', '12', 'b', 2),
('¿En qué deporte se usa el término home run?', 'Cricket', 'Béisbol', 'Softbol', 'Rugby', 'b', 2),
('¿Qué piloto argentino ganó cinco campeonatos de Fórmula 1?', 'Reutemann', 'Juan Manuel Fangio', 'Froilán González', 'Zanardi', 'b', 2),
('¿Qué selección de rugby es conocida como los All Blacks?', 'Australia', 'Nueva Zelanda', 'Sudáfrica', 'Inglaterra', 'b', 2),
('¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos?', 'París', 'Atenas', 'Londres', 'Roma', 'b', 2),
('¿Qué jugador es conocido como CR7?', 'Neymar', 'Cristiano Ronaldo', 'Ronaldinho', 'Ronaldo Nazário', 'b', 2),
('¿Cuál es la competición de clubes más importante de Sudamérica en fútbol?', 'Champions League', 'Copa Libertadores', 'Copa América', 'Recopa', 'b', 2),
('¿En qué deporte compiten los Chicago Bulls?', 'Béisbol', 'Básquet', 'Fútbol americano', 'Hockey', 'b', 2),
('¿Qué tenista ganó más títulos de Grand Slam entre los hombres (histórico reciente)?', 'Federer', 'Nadal', 'Djokovic', 'Sampras', 'c', 2),
('¿Cuántos jugadores hay en un equipo de handball en cancha?', '6', '7', '5', '8', 'b', 2),
('¿En qué país nació el basquetbol?', 'Canadá', 'Estados Unidos', 'Inglaterra', 'Francia', 'b', 2),
('¿Qué selección ganó la Copa América 2021?', 'Brasil', 'Argentina', 'Uruguay', 'Chile', 'b', 2),
('¿Qué distancia tiene una carrera de 400 metros con vallas?', '200 m', '400 m', '800 m', '100 m', 'b', 2),
('¿En qué deporte se usa el término set point?', 'Fútbol', 'Tenis', 'Golf', 'Boxeo', 'b', 2),
('¿Qué país domina históricamente el ping pong o tenis de mesa?', 'Japón', 'China', 'Corea', 'Alemania', 'b', 2),
('¿En qué disciplina compite un decatleta?', 'Un solo deporte', 'Diez pruebas de atletismo', 'Natación combinada', 'Ciclismo', 'b', 2),
('¿Qué jugador de fútbol usó la camiseta número 10 y ganó el Mundial 1986 con Argentina?', 'Kempes', 'Maradona', 'Batistuta', 'Passarella', 'b', 2),
('¿Qué equipo inglés juega en el estadio Old Trafford?', 'Liverpool', 'Manchester United', 'Chelsea', 'Arsenal', 'b', 2),
('¿En qué deporte se destaca Novak Djokovic?', 'Golf', 'Tenis', 'Fútbol', 'Cricket', 'b', 2),
('¿Cuántos anillos de campeón necesita ganar un equipo para el título de la NBA en una temporada?', 'Varios', 'Uno', 'Tres', 'Dos', 'b', 2),
('¿Qué país ganó la primera Copa del Mundo de fútbol en 1930?', 'Argentina', 'Uruguay', 'Brasil', 'Italia', 'b', 2),
('¿En qué deporte se corre la Vuelta a España?', 'Automovilismo', 'Ciclismo', 'Motociclismo', 'Atletismo', 'b', 2),
('¿Qué boxeador se autodenominó El más grande y fue campeón peso pesado?', 'Mike Tyson', 'Muhammad Ali', 'Joe Frazier', 'George Foreman', 'b', 2),
('¿En qué deporte destacó Diego Maradona además del fútbol de clubes?', 'Básquet', 'Fútbol de selección', 'Tenis', 'Vóley', 'b', 2),
('¿Cuántos jugadores tiene un equipo de water polo en el agua?', '5', '7', '6', '8', 'b', 2),
('¿Qué país fue sede del Mundial de fútbol 2010?', 'Brasil', 'Sudáfrica', 'Alemania', 'Rusia', 'b', 2),
('¿En qué deporte se otorga la camiseta amarilla al líder?', 'Automovilismo', 'Ciclismo', 'Atletismo', 'Natación', 'b', 2);

-- ---------- DEPORTES - NIVEL 3 (DIFICIL) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿En qué año se celebraron los primeros Juegos Olímpicos modernos?', '1892', '1896', '1900', '1904', 'b', 2),
('¿Qué tenista suizo ganó 20 títulos de Grand Slam?', 'Nadal', 'Roger Federer', 'Djokovic', 'Wawrinka', 'b', 2),
('¿En qué ciudad se disputó la final del Mundial 2014?', 'São Paulo', 'Río de Janeiro', 'Brasilia', 'Belo Horizonte', 'b', 2),
('¿Quién fue el primer futbolista en ganar cinco Balones de Oro consecutivos?', 'Cristiano Ronaldo', 'Lionel Messi', 'Michel Platini', 'Johan Cruyff', 'b', 2),
('¿En qué año se disputó el famoso Maracanazo?', '1930', '1950', '1958', '1962', 'b', 2),
('¿Qué piloto tiene el récord de más títulos de Fórmula 1 (compartido)?', 'Ayrton Senna', 'Michael Schumacher', 'Alain Prost', 'Sebastian Vettel', 'b', 2),
('¿Cuántas medallas de oro ganó Michael Phelps en total en su carrera olímpica?', '18', '23', '28', '15', 'b', 2),
('¿Qué país ganó el primer Mundial de rugby en 1987?', 'Australia', 'Nueva Zelanda', 'Sudáfrica', 'Inglaterra', 'b', 2),
('¿Quién marcó el gol conocido como La Mano de Dios?', 'Pelé', 'Maradona', 'Kempes', 'Valdano', 'b', 2),
('¿En qué año Usain Bolt estableció el récord mundial de 100 m con 9.58 s?', '2008', '2009', '2012', '2015', 'b', 2),
('¿Qué equipo ganó la primera edición de la Copa Libertadores en 1960?', 'Peñarol', 'Independiente', 'Santos', 'River Plate', 'a', 2),
('¿Cuál es el único país que ha jugado todos los Mundiales de fútbol?', 'Argentina', 'Brasil', 'Alemania', 'Italia', 'b', 2),
('¿Quién ganó el Tour de Francia siete veces consecutivas antes de ser desposeído?', 'Miguel Indurain', 'Lance Armstrong', 'Eddy Merckx', 'Chris Froome', 'b', 2),
('¿En qué año la selección española ganó su único Mundial de fútbol?', '2006', '2010', '2014', '2008', 'b', 2),
('¿Qué jugador de la NBA anotó 100 puntos en un solo partido?', 'Michael Jordan', 'Wilt Chamberlain', 'Kobe Bryant', 'Kareem Abdul-Jabbar', 'b', 2),
('¿Qué país ganó el Mundial de básquet FIBA 2019?', 'Estados Unidos', 'España', 'Argentina', 'Francia', 'b', 2),
('¿Quién fue la primera gimnasta en obtener un 10 perfecto en unos Juegos Olímpicos?', 'Simone Biles', 'Nadia Comaneci', 'Olga Korbut', 'Mary Lou Retton', 'b', 2),
('¿En qué año se creó la Champions League con ese nombre?', '1955', '1992', '1999', '1987', 'b', 2),
('¿Qué boxeador venció a Muhammad Ali en la Pelea del Siglo de 1971?', 'George Foreman', 'Joe Frazier', 'Ken Norton', 'Sonny Liston', 'b', 2),
('¿Cuál fue el primer país africano en llegar a cuartos de final de un Mundial?', 'Nigeria', 'Camerún', 'Senegal', 'Ghana', 'b', 2),
('¿Quién ostenta el récord de más goles en una sola edición de Copa del Mundo (13)?', 'Pelé', 'Just Fontaine', 'Gerd Müller', 'Ronaldo', 'b', 2),
('¿En qué año se disputó el primer Super Bowl?', '1958', '1967', '1970', '1975', 'b', 2),
('¿Qué tenista completó el Golden Slam en 1988?', 'Martina Navratilova', 'Steffi Graf', 'Chris Evert', 'Monica Seles', 'b', 2),
('¿Qué equipo inglés fue campeón invicto de la Premier League en 2003-2004?', 'Manchester United', 'Arsenal', 'Chelsea', 'Liverpool', 'b', 2),
('¿Quién fue el máximo goleador histórico de la selección brasileña hasta hace pocos años?', 'Ronaldo', 'Pelé', 'Romário', 'Neymar', 'b', 2),
('¿En qué año se realizaron los Juegos Olímpicos de Barcelona?', '1988', '1992', '1996', '2000', 'b', 2),
('¿Qué velocista estadounidense ganó cuatro oros en Berlín 1936?', 'Carl Lewis', 'Jesse Owens', 'Bob Hayes', 'Ralph Metcalfe', 'b', 2),
('¿Cuál es el estadio con mayor capacidad usado en Mundiales, escenario del Maracanazo?', 'Wembley', 'Maracaná', 'Azteca', 'San Siro', 'b', 2),
('¿Quién ganó el primer Mundial de Fórmula 1 en 1950?', 'Fangio', 'Giuseppe Farina', 'Alberto Ascari', 'Stirling Moss', 'b', 2),
('¿Qué país ganó la medalla de oro en fútbol masculino en los Juegos de 2008?', 'Brasil', 'Argentina', 'Nigeria', 'España', 'b', 2),
('¿Cuántos Grand Slam de tenis ganó Rod Laver en total?', '8', '11', '14', '6', 'b', 2),
('¿Qué equipo ganó las primeras tres Champions/Copas de Europa consecutivas en los años 50?', 'Benfica', 'Real Madrid', 'Milan', 'Ajax', 'b', 2),
('¿En qué año se incorporó el fútbol femenino a los Juegos Olímpicos?', '1992', '1996', '2000', '2004', 'b', 2),
('¿Quién es el máximo anotador histórico de la NBA (récord actual)?', 'Kareem Abdul-Jabbar', 'LeBron James', 'Karl Malone', 'Michael Jordan', 'b', 2),
('¿Qué selección ganó el Mundial de fútbol de 1954 en la Final de Berna?', 'Hungría', 'Alemania Occidental', 'Brasil', 'Uruguay', 'b', 2),
('¿Quién fue el primer sudamericano en ganar un título de Grand Slam en tenis masculino en la era abierta?', 'Guillermo Vilas', 'Gustavo Kuerten', 'Marcelo Ríos', 'David Nalbandian', 'a', 2),
('¿En qué año se disputó el famoso Milagro sobre el hielo entre EE.UU. y la URSS en hockey?', '1976', '1980', '1984', '1972', 'b', 2),
('¿Qué maratonista etíope corrió descalzo y ganó el oro en Roma 1960?', 'Haile Gebrselassie', 'Abebe Bikila', 'Kenenisa Bekele', 'Mamo Wolde', 'b', 2),
('¿Qué país ganó la primera Eurocopa en 1960?', 'España', 'Unión Soviética', 'Yugoslavia', 'Francia', 'b', 2),
('¿Quién ganó el Balón de Oro en 2006 tras el Mundial de Alemania?', 'Zidane', 'Fabio Cannavaro', 'Ronaldinho', 'Henry', 'b', 2),
('¿En qué edición olímpica se boicotearon los Juegos por parte de EE.UU. (Moscú)?', '1976', '1980', '1984', '1988', 'b', 2),
('¿Qué jugador holandés fue figura del fútbol total en los años 70?', 'Gullit', 'Johan Cruyff', 'Van Basten', 'Neeskens', 'b', 2),
('¿Cuál fue el primer equipo argentino en ganar la Copa Intercontinental?', 'Boca Juniors', 'Racing Club', 'Independiente', 'Estudiantes', 'b', 2),
('¿En qué año ganó Argentina la medalla de oro olímpica en básquet?', '2000', '2004', '2008', '2012', 'b', 2),
('¿Qué golfista tiene el récord de más majors ganados?', 'Tiger Woods', 'Jack Nicklaus', 'Arnold Palmer', 'Gary Player', 'b', 2),
('¿Quién fue el goleador del Mundial 2018?', 'Cristiano Ronaldo', 'Harry Kane', 'Kylian Mbappé', 'Romelu Lukaku', 'b', 2),
('¿Qué país ganó el primer Mundial Femenino de fútbol en 1991?', 'Noruega', 'Estados Unidos', 'Alemania', 'China', 'b', 2),
('¿Cuál fue la primera mujer en ganar el Tour de France femenino moderno reinstaurado en 2022?', 'Marianne Vos', 'Annemiek van Vleuten', 'Demi Vollering', 'Lizzie Deignan', 'b', 2),
('¿En qué año Ayrton Senna ganó su primer título mundial de F1?', '1988', '1990', '1991', '1985', 'a', 2),
('¿Qué selección de cricket es históricamente dominante junto a India y Inglaterra?', 'Sudáfrica', 'Australia', 'Pakistán', 'Sri Lanka', 'b', 2);


-- ============================================================================
-- CULTURA (categoria_id = 3)
-- ============================================================================

-- ---------- CULTURA - NIVEL 1 (FACIL) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿Cuál es la capital de Francia?', 'Londres', 'París', 'Roma', 'Madrid', 'b', 3),
('¿Cuántos lados tiene un triángulo?', '2', '3', '4', '5', 'b', 3),
('¿De qué color es el cielo en un día despejado?', 'Verde', 'Azul', 'Rojo', 'Amarillo', 'b', 3),
('¿Cuántos días tiene una semana?', '5', '6', '7', '8', 'c', 3),
('¿Qué animal es conocido como el mejor amigo del hombre?', 'Gato', 'Perro', 'Caballo', 'Conejo', 'b', 3),
('¿Cuál es el planeta en el que vivimos?', 'Marte', 'Tierra', 'Júpiter', 'Venus', 'b', 3),
('¿De qué animal obtenemos la lana?', 'Vaca', 'Oveja', 'Gallina', 'Cerdo', 'b', 3),
('¿Cuántos colores tiene el arcoíris?', '5', '6', '7', '8', 'c', 3),
('¿Qué se necesita para ver en la oscuridad de una casa?', 'Agua', 'Luz', 'Comida', 'Ruido', 'b', 3),
('¿Cuál es el idioma que se habla en Brasil?', 'Español', 'Portugués', 'Inglés', 'Francés', 'b', 3),
('¿Cuántas patas tiene una araña?', '6', '8', '4', '10', 'b', 3),
('¿Qué instrumento tiene teclas blancas y negras?', 'Guitarra', 'Piano', 'Violín', 'Flauta', 'b', 3),
('¿Cuál es el rey de la selva?', 'Tigre', 'León', 'Elefante', 'Oso', 'b', 3),
('¿Qué usamos para leer cuando no vemos bien?', 'Guantes', 'Anteojos', 'Sombrero', 'Zapatos', 'b', 3),
('¿Cuántos meses tiene un año?', '10', '11', '12', '13', 'c', 3),
('¿Qué fruta es amarilla y curva, y les gusta a los monos?', 'Manzana', 'Banana', 'Uva', 'Pera', 'b', 3),
('¿De qué color es la nieve?', 'Negra', 'Blanca', 'Verde', 'Azul', 'b', 3),
('¿Qué animal dice muuu?', 'Perro', 'Vaca', 'Gato', 'Pato', 'b', 3),
('¿Cuál es la capital de España?', 'Barcelona', 'Madrid', 'Sevilla', 'Valencia', 'b', 3),
('¿En qué estación del año hace más calor?', 'Invierno', 'Verano', 'Otoño', 'Primavera', 'b', 3),
('¿Qué órgano usamos para respirar?', 'Corazón', 'Pulmones', 'Hígado', 'Estómago', 'b', 3),
('¿Cuántas horas tiene un día?', '12', '24', '48', '10', 'b', 3),
('¿Qué animal vuela y hace miel?', 'Mariposa', 'Abeja', 'Mosca', 'Hormiga', 'b', 3),
('¿Cuál es el color que se forma al mezclar azul y amarillo?', 'Rojo', 'Verde', 'Naranja', 'Violeta', 'b', 3),
('¿Qué usamos para escribir en un pizarrón?', 'Lápiz', 'Tiza', 'Pincel', 'Crayón', 'b', 3),
('¿Cuál es el animal más grande del mar?', 'Tiburón', 'Ballena azul', 'Delfín', 'Pulpo', 'b', 3),
('¿Qué se usa para cortar el pelo?', 'Cuchara', 'Tijera', 'Martillo', 'Regla', 'b', 3),
('¿Cuál es el idioma oficial de Argentina?', 'Portugués', 'Español', 'Inglés', 'Italiano', 'b', 3),
('¿Qué planeta es conocido como el planeta rojo?', 'Venus', 'Marte', 'Júpiter', 'Saturno', 'b', 3),
('¿Qué animal es famoso por dar saltos y llevar a su cría en una bolsa?', 'Koala', 'Canguro', 'Conejo', 'Rana', 'b', 3),
('¿Qué comen normalmente los conejos?', 'Carne', 'Zanahorias', 'Pescado', 'Pan', 'b', 3),
('¿Cuál es la capital de Italia?', 'Milán', 'Roma', 'Nápoles', 'Turín', 'b', 3),
('¿Qué usamos para saber la hora?', 'Termómetro', 'Reloj', 'Regla', 'Brújula', 'b', 3),
('¿Cuál es el color del sol tal como lo vemos?', 'Azul', 'Amarillo', 'Verde', 'Rojo', 'b', 3),
('¿Qué parte del cuerpo usamos para oír?', 'Nariz', 'Orejas', 'Ojos', 'Boca', 'b', 3),
('¿Qué animal es conocido por ser muy lento?', 'Liebre', 'Tortuga', 'Perro', 'Caballo', 'b', 3),
('¿Cuántos ojos tiene una persona normalmente?', '1', '2', '3', '4', 'b', 3),
('¿Qué bebida se obtiene de las vacas?', 'Jugo', 'Leche', 'Agua', 'Refresco', 'b', 3),
('¿Cuál es el continente donde vive el canguro de forma natural?', 'África', 'Australia', 'Asia', 'Europa', 'b', 3),
('¿Qué usamos para protegernos de la lluvia?', 'Ventilador', 'Paraguas', 'Anteojos', 'Bufanda', 'b', 3),
('¿Qué fruta es roja por fuera y crece en árboles, asociada a la salud?', 'Banana', 'Manzana', 'Limón', 'Uva', 'b', 3),
('¿Qué animal ladra?', 'Gato', 'Perro', 'Vaca', 'Caballo', 'b', 3),
('¿Cuál es la primera letra del abecedario?', 'B', 'A', 'C', 'Z', 'b', 3),
('¿Qué se usa para lavarse las manos además del agua?', 'Aceite', 'Jabón', 'Azúcar', 'Sal', 'b', 3),
('¿Qué astro ilumina la noche?', 'El sol', 'La luna', 'Marte', 'Una nube', 'b', 3),
('¿Cuál es el color de la hierba sana?', 'Azul', 'Verde', 'Rojo', 'Negro', 'b', 3),
('¿Qué animal maúlla?', 'Perro', 'Gato', 'Pato', 'Vaca', 'b', 3),
('¿Cuántas ruedas tiene una bicicleta?', '1', '2', '3', '4', 'b', 3),
('¿Qué usamos en los pies para caminar en la calle?', 'Guantes', 'Zapatos', 'Sombrero', 'Bufanda', 'b', 3),
('¿Qué se celebra el 1 de enero?', 'Navidad', 'Año Nuevo', 'Pascua', 'Día del Niño', 'b', 3);

-- ---------- CULTURA - NIVEL 2 (INTERMEDIO) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿Cuál es el océano más grande del mundo?', 'Atlántico', 'Pacífico', 'Índico', 'Ártico', 'b', 3),
('¿Cuál es el planeta más cercano al Sol?', 'Venus', 'Mercurio', 'Marte', 'Tierra', 'b', 3),
('¿Cuál es el idioma más hablado del mundo por número de nativos?', 'Inglés', 'Chino mandarín', 'Español', 'Hindi', 'b', 3),
('¿Quién escribió la obra Romeo y Julieta?', 'Cervantes', 'Shakespeare', 'Molière', 'Dante', 'b', 3),
('¿Cuál es el metal líquido a temperatura ambiente?', 'Plomo', 'Mercurio', 'Hierro', 'Estaño', 'b', 3),
('¿Cuántos huesos tiene aproximadamente el cuerpo humano adulto?', '150', '206', '300', '250', 'b', 3),
('¿Cuál es el río más largo del mundo (según la mayoría de fuentes)?', 'Nilo', 'Amazonas', 'Yangtsé', 'Misisipi', 'a', 3),
('¿Qué gas necesitan las plantas para la fotosíntesis?', 'Oxígeno', 'Dióxido de carbono', 'Nitrógeno', 'Hidrógeno', 'b', 3),
('¿Cuál es la capital de Japón?', 'Kioto', 'Tokio', 'Osaka', 'Nagoya', 'b', 3),
('¿Quién pintó el cuadro La noche estrellada?', 'Monet', 'Van Gogh', 'Picasso', 'Dalí', 'b', 3),
('¿Cuál es el símbolo químico del agua?', 'CO2', 'H2O', 'O2', 'NaCl', 'b', 3),
('¿Cuál es el continente más grande del mundo?', 'África', 'Asia', 'América', 'Europa', 'b', 3),
('¿En qué país se encuentra la ciudad de El Cairo?', 'Marruecos', 'Egipto', 'Argelia', 'Libia', 'b', 3),
('¿Qué instrumento científico se usa para ver cosas muy pequeñas?', 'Telescopio', 'Microscopio', 'Termómetro', 'Barómetro', 'b', 3),
('¿Cuál es la moneda oficial de Japón?', 'Yuan', 'Yen', 'Won', 'Dólar', 'b', 3),
('¿Qué planeta es el más grande del sistema solar?', 'Saturno', 'Júpiter', 'Neptuno', 'Urano', 'b', 3),
('¿Quién escribió Cien años de soledad?', 'Borges', 'Gabriel García Márquez', 'Vargas Llosa', 'Cortázar', 'b', 3),
('¿Cuál es el hueso más largo del cuerpo humano?', 'Húmero', 'Fémur', 'Tibia', 'Columna', 'b', 3),
('¿En qué país se originaron los Juegos Olímpicos y la filosofía occidental?', 'Roma', 'Grecia', 'Egipto', 'Persia', 'b', 3),
('¿Cuál es la capital de Australia?', 'Sídney', 'Canberra', 'Melbourne', 'Brisbane', 'b', 3),
('¿Qué órgano bombea la sangre en el cuerpo?', 'Pulmón', 'Corazón', 'Hígado', 'Riñón', 'b', 3),
('¿Quién propuso la teoría de la evolución por selección natural?', 'Newton', 'Charles Darwin', 'Mendel', 'Lamarck', 'b', 3),
('¿Cuál es el país más poblado del mundo actualmente (aprox. reciente)?', 'China', 'India', 'Estados Unidos', 'Indonesia', 'b', 3),
('¿Qué idioma se habla oficialmente en Egipto?', 'Persa', 'Árabe', 'Turco', 'Francés', 'b', 3),
('¿Qué famoso científico formuló la ley de la gravedad?', 'Einstein', 'Isaac Newton', 'Galileo', 'Kepler', 'b', 3),
('¿Cuál es el desierto más grande y cálido del mundo?', 'Gobi', 'Sahara', 'Atacama', 'Kalahari', 'b', 3),
('¿Cuál es la capital de Canadá?', 'Toronto', 'Ottawa', 'Montreal', 'Vancouver', 'b', 3),
('¿Qué compositor era sordo cuando escribió gran parte de su obra?', 'Mozart', 'Beethoven', 'Bach', 'Chopin', 'b', 3),
('¿Qué vitamina obtenemos principalmente del sol?', 'Vitamina A', 'Vitamina D', 'Vitamina C', 'Vitamina B12', 'b', 3),
('¿Cuál es la montaña más alta de América?', 'Everest', 'Aconcagua', 'Mont Blanc', 'Kilimanjaro', 'b', 3),
('¿Qué escritora escribió Harry Potter?', 'Agatha Christie', 'J. K. Rowling', 'Jane Austen', 'Suzanne Collins', 'b', 3),
('¿Cuál es la capital de Alemania?', 'Múnich', 'Berlín', 'Hamburgo', 'Fráncfort', 'b', 3),
('¿Qué elemento químico tiene el símbolo O?', 'Oro', 'Oxígeno', 'Osmio', 'Oganesón', 'b', 3),
('¿En qué museo se encuentra La Mona Lisa?', 'Prado', 'Louvre', 'MoMA', 'Uffizi', 'b', 3),
('¿Cuál es el mamífero terrestre más grande?', 'Rinoceronte', 'Elefante africano', 'Hipopótamo', 'Jirafa', 'b', 3),
('¿Qué planeta tiene anillos muy visibles?', 'Marte', 'Saturno', 'Venus', 'Mercurio', 'b', 3),
('¿Cuál es la capital de Rusia?', 'San Petersburgo', 'Moscú', 'Kiev', 'Minsk', 'b', 3),
('¿Qué célula transporta el oxígeno en la sangre?', 'Glóbulos blancos', 'Glóbulos rojos', 'Plaquetas', 'Neuronas', 'b', 3),
('¿Quién escribió la Divina Comedia?', 'Petrarca', 'Dante Alighieri', 'Boccaccio', 'Virgilio', 'b', 3),
('¿Cuál es el país con mayor superficie del mundo?', 'Canadá', 'Rusia', 'China', 'Estados Unidos', 'b', 3),
('¿Qué gas es el más abundante en la atmósfera terrestre?', 'Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Hidrógeno', 'b', 3),
('¿Cuál es la capital de Egipto?', 'Alejandría', 'El Cairo', 'Guiza', 'Luxor', 'b', 3),
('¿Qué pintor español creó el Guernica?', 'Dalí', 'Picasso', 'Miró', 'Goya', 'b', 3),
('¿Cuál es la estrella más cercana a la Tierra?', 'Sirio', 'El Sol', 'Alfa Centauri', 'Polaris', 'b', 3),
('¿En qué país se encuentra la Torre de Pisa?', 'España', 'Italia', 'Grecia', 'Francia', 'b', 3),
('¿Qué órgano del cuerpo produce la insulina?', 'Hígado', 'Páncreas', 'Riñón', 'Estómago', 'b', 3),
('¿Cuál es la capital de Portugal?', 'Oporto', 'Lisboa', 'Coímbra', 'Braga', 'b', 3),
('¿Qué científica ganó dos premios Nobel en distintas ciencias?', 'Rosalind Franklin', 'Marie Curie', 'Ada Lovelace', 'Jane Goodall', 'b', 3),
('¿Cuál es el animal terrestre más rápido?', 'León', 'Guepardo', 'Caballo', 'Antílope', 'b', 3),
('¿Qué instrumento mide la temperatura?', 'Barómetro', 'Termómetro', 'Higrómetro', 'Anemómetro', 'b', 3);

-- ---------- CULTURA - NIVEL 3 (DIFICIL) ----------
INSERT INTO preguntas (pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, categoria_id) VALUES
('¿En qué año se publicó la primera parte del Quijote?', '1585', '1605', '1615', '1620', 'b', 3),
('¿Cuál es el elemento químico con símbolo Au?', 'Plata', 'Oro', 'Aluminio', 'Argón', 'b', 3),
('¿Cuál es la montaña más alta del mundo?', 'K2', 'Everest', 'Kangchenjunga', 'Lhotse', 'b', 3),
('¿Qué físico propuso el principio de incertidumbre?', 'Bohr', 'Heisenberg', 'Schrödinger', 'Planck', 'b', 3),
('¿Cuál es la unidad básica de la herencia genética?', 'Célula', 'Gen', 'Cromosoma', 'Proteína', 'b', 3),
('¿Qué filósofo escribió La República?', 'Aristóteles', 'Platón', 'Sócrates', 'Kant', 'b', 3),
('¿Cuál es el metal más abundante en la corteza terrestre?', 'Hierro', 'Aluminio', 'Cobre', 'Calcio', 'b', 3),
('¿Quién compuso la ópera La flauta mágica?', 'Beethoven', 'Mozart', 'Verdi', 'Wagner', 'b', 3),
('¿Cuál es la velocidad de la luz en el vacío (aproximada)?', '150.000 km/s', '300.000 km/s', '1.000.000 km/s', '30.000 km/s', 'b', 3),
('¿En qué país se encuentra la ciudad de Tombuctú?', 'Marruecos', 'Malí', 'Egipto', 'Sudán', 'b', 3),
('¿Qué escritor argentino escribió Ficciones y El Aleph?', 'Cortázar', 'Borges', 'Sabato', 'Bioy Casares', 'b', 3),
('¿Cuál es el número atómico del carbono?', '4', '6', '8', '12', 'b', 3),
('¿Qué pintor renacentista pintó el techo de la Capilla Sixtina?', 'Rafael', 'Miguel Ángel', 'Botticelli', 'Tiziano', 'b', 3),
('¿Cuál es el planeta más frío del sistema solar?', 'Neptuno', 'Urano', 'Saturno', 'Plutón', 'b', 3),
('¿Qué matemático griego es conocido como el padre de la geometría?', 'Pitágoras', 'Euclides', 'Arquímedes', 'Tales', 'b', 3),
('¿En qué año cayó el Imperio Bizantino con la toma de Constantinopla?', '1453', '1492', '1521', '1400', 'a', 3),
('¿Cuál es el hueso más pequeño del cuerpo humano?', 'El martillo', 'El estribo', 'El yunque', 'La falange', 'b', 3),
('¿Qué escritor ruso escribió Guerra y Paz?', 'Dostoyevski', 'Tolstói', 'Chéjov', 'Gógol', 'b', 3),
('¿Cuál es la capital de Kazajistán?', 'Almatý', 'Astaná', 'Taskent', 'Biskek', 'b', 3),
('¿Qué partícula subatómica tiene carga negativa?', 'Protón', 'Electrón', 'Neutrón', 'Positrón', 'b', 3),
('¿Quién formuló las leyes del movimiento planetario?', 'Copérnico', 'Kepler', 'Galileo', 'Newton', 'b', 3),
('¿Cuál es el idioma con mayor número de caracteres o signos de escritura?', 'Japonés', 'Chino', 'Coreano', 'Árabe', 'b', 3),
('¿Qué elemento químico tiene el símbolo Fe?', 'Flúor', 'Hierro', 'Fermio', 'Fósforo', 'b', 3),
('¿Qué compositor alemán escribió El anillo del nibelungo?', 'Bach', 'Wagner', 'Brahms', 'Handel', 'b', 3),
('¿En qué año se produjo la caída de la Bastilla?', '1776', '1789', '1799', '1804', 'b', 3),
('¿Cuál es la capital de Marruecos?', 'Casablanca', 'Rabat', 'Marrakech', 'Fez', 'b', 3),
('¿Qué científico desarrolló la tabla periódica de los elementos?', 'Bohr', 'Mendeléyev', 'Dalton', 'Lavoisier', 'b', 3),
('¿Cuál es el río más largo de África?', 'Congo', 'Nilo', 'Níger', 'Zambeze', 'b', 3),
('¿Qué escritor irlandés escribió Ulises?', 'Oscar Wilde', 'James Joyce', 'Samuel Beckett', 'W. B. Yeats', 'b', 3),
('¿Cuál es el símbolo químico del sodio?', 'So', 'Na', 'Sd', 'S', 'b', 3),
('¿Qué pintor holandés se cortó parte de una oreja?', 'Rembrandt', 'Van Gogh', 'Vermeer', 'Mondrian', 'b', 3),
('¿En qué año se firmó la Declaración Universal de los Derechos Humanos?', '1945', '1948', '1950', '1955', 'b', 3),
('¿Cuál es la capital de Nueva Zelanda?', 'Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'b', 3),
('¿Qué teoría explica el origen del universo con una gran explosión?', 'Teoría del estado estacionario', 'Teoría del Big Bang', 'Teoría de cuerdas', 'Teoría cuántica', 'b', 3),
('¿Qué filósofo escribió Así habló Zaratustra?', 'Kant', 'Nietzsche', 'Hegel', 'Schopenhauer', 'b', 3),
('¿Cuál es el planeta con el día más largo (rotación más lenta)?', 'Mercurio', 'Venus', 'Marte', 'Júpiter', 'b', 3),
('¿Qué instrumento se usa para medir la presión atmosférica?', 'Termómetro', 'Barómetro', 'Higrómetro', 'Anemómetro', 'b', 3),
('¿Qué escritor colombiano ganó el Premio Nobel de Literatura en 1982?', 'Vargas Llosa', 'García Márquez', 'Neruda', 'Paz', 'b', 3),
('¿Cuál es el número aproximado de elementos de la tabla periódica actual?', '92', '118', '150', '100', 'b', 3),
('¿Qué civilización inventó el concepto del cero de forma independiente en América?', 'Inca', 'Maya', 'Azteca', 'Olmeca', 'b', 3),
('¿Cuál es la capital de Suiza?', 'Zúrich', 'Berna', 'Ginebra', 'Basilea', 'b', 3),
('¿Qué gas noble se usa en los letreros luminosos rojos?', 'Argón', 'Neón', 'Helio', 'Kriptón', 'b', 3),
('¿Qué pintor pintó Las meninas?', 'Goya', 'Velázquez', 'El Greco', 'Murillo', 'b', 3),
('¿Cuál es el órgano más grande del cuerpo humano?', 'Hígado', 'La piel', 'Pulmón', 'Intestino', 'b', 3),
('¿En qué año llegó el ser humano a la Luna por primera vez?', '1961', '1969', '1972', '1975', 'b', 3),
('¿Qué matemático suizo introdujo gran parte de la notación moderna, como e y f(x)?', 'Gauss', 'Euler', 'Fermat', 'Leibniz', 'b', 3),
('¿Cuál es la capital de Islandia?', 'Oslo', 'Reikiavik', 'Helsinki', 'Copenhague', 'b', 3),
('¿Qué escritor escribió Crimen y castigo?', 'Tolstói', 'Dostoyevski', 'Turguéniev', 'Pushkin', 'b', 3),
('¿Cuál es la partícula portadora de la fuerza electromagnética?', 'Gluón', 'Fotón', 'Bosón W', 'Gravitón', 'b', 3),
('¿Qué antiguo idioma se usaba en el Imperio Romano?', 'Griego', 'Latín', 'Etrusco', 'Sánscrito', 'b', 3);
